### PR TITLE
[asl] Obfuscation of locals in primitives

### LINKED ISSUE #1014: `N` is a defined identifier in ASLRef
Reproduce steps:
1.
```bash
$ cat > mwe.asl <<EOF
config N : integer = 0;
func main () => integer begin return 0; end
EOF
```
2.
```bash
$ dune exec aslref mwe.asl
```

Actual behavior: `ASL Typing error: cannot declare already declared element "N".`
Expected behavior: exit with 0

### PR DESCRIPTION
**Pull request by HadrienRenaud**
Until now, we were only obfuscating locals in the standard library. This now implements obfuscation for primitives.

Fix #1014

### CODE REVIEW

File: asllib/ASTUtils.ml [hunk 1]
```diff
@@ -756,9 +757,10 @@ let rename_locals map_name ast =
     | Slice_Star (e1, e2) -> Slice_Star (map_e e1, map_e e2)
   and map_t t =
     map_desc_st' t @@ function
-    | T_Real | T_String | T_Bool | T_Enum _ | T_Named _
-    | T_Int (UnConstrained | Parameterized _) ->
+    | T_Real | T_String | T_Bool | T_Enum _ | T_Named _ | T_Int UnConstrained ->
         t.desc
+    | T_Int (Parameterized _) ->
+        failwith "Not yet implemented: offuscate parametrized types"
```
Comment (yuxiliu-arm) [inline asllib/ASTUtils.ml:763]:
```suggestion
        failwith "Not yet implemented: obfuscate parametrized types"
```

**Review by yuxiliu-arm — APPROVED** [review]
